engines:
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - CUSTOM
      - TODO
  markdownlint:
    enabled: true

ratings:
  paths:
  - *.R
  - *.r
  - *.md
exclude_paths:
- tests/*