language: R
sudo: false
warnings_are_errors: false
cache: packages

before_script:
  - Rscript -e 'install.packages(c("covr", "testthat"), repos = "https://cloud.r-project.org")'

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
