language: R
sudo: false
warnings_are_errors: false
cache: packages

r_github_packages:
  - jimhester/covr
  - hadley/testthat

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
